# Generated by Django 5.0.4 on 2024-05-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="grp_profile",
            field=models.ImageField(blank=True, null=True, upload_to="grp_profile/"),
        ),
    ]
