# Generated by Django 5.0.4 on 2024-05-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_rename_grp_profile_group_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="profile_image",
        ),
        migrations.AddField(
            model_name="group",
            name="grp_image",
            field=models.ImageField(blank=True, null=True, upload_to="grp_image/"),
        ),
    ]
